### PR TITLE
add apiURL file

### PR DESCRIPTION
**Pull request by tushar1-000**
In this pull request, I have created a file apiURL.js in which I have added the API URL and imported it into the file where it was hard coded.

### CODE REVIEW

**Comment by micahlt** [comment]
There are several lines in this PR where you have templates (`${apiURL}`) inside normal strings, not backticks, which doesn't work.  Until those are resolved, this is not mergeable.

**Comment by tushar1-000** [comment]
Ok I will resolve those issues today .

**Comment by micahlt** [comment]
Thank you for your contributions!

**Comment by tushar1-000** [comment]
I have made a new commit in which I changed the  '' to `` and also add another URL  export https://wasteof.money to the apiURL file.

**Comment by tushar1-000** [comment]
Hey, @micahlt  can you help me why these checks are not passing?

**Comment by micahlt** [comment]
@tushar1-000 I'm not sure what's wrong - it could simply be a problem with the GitHub Action.  I'll have to pull this change and test it on my personal machine.

**Comment by tushar1-000** [comment]
ok

**Comment by micahlt** [comment]
Looks good!  Thank you @tushar1-000 for this PR!

**Pull request merged**
